/** Stable market error codes (§51). */
export type MarketErrorCode =
  | "MARKET_DISABLED"
  | "INDEXER_UNHEALTHY"
  | "INDEXER_BEHIND"
  | "INDEXER_REBUILDING"
  | "INDEXER_DIVERGED"
  | "TOKEN_NOT_FOUND"
  | "LISTING_BAD_VERSION"
  | "LISTING_BAD_SIGNATURE"
  | "LISTING_BAD_SOURCE"
  | "LISTING_SOURCE_SPENT"
  | "LISTING_SOURCE_SPENT_PENDING"
  | "LISTING_SOURCE_MISMATCH"
  | "LISTING_TOKEN_MISMATCH"
  | "LISTING_AMOUNT_INVALID"
  | "LISTING_PRICE_INVALID"
  | "LISTING_INPUT_ALREADY_LOCKED"
  | "LISTING_EXPIRED"
  | "LISTING_CANCELLED"
  | "LISTING_INVALIDATED"
  | "LISTING_RESERVED"
  | "LISTING_NOT_EXECUTABLE"
  | "SELLER_PAYOUT_DUST"
  | "MARKET_FEE_DUST"
  | "P2P_SETTLEMENT_CAP_EXCEEDED"
  | "CHAIN_IDENTITY_MISMATCH"
  | "RESERVATION_CONFLICT"
  | "RESERVATION_EXPIRED"
  | "BUYER_INPUT_INVALID"
  | "BUYER_INPUT_SPENT"
  | "BUYER_FUNDS_INSUFFICIENT"
  | "PSBT_MUTATED"
  | "BUYER_SIGNATURE_INVALID"
  | "SELLER_SIGNATURE_INVALID"
  | "UNSAFE_SIGHASH"
  | "MARKET_VALIDATION_FAILED"
  | "MEMPOOL_REJECTED"
  | "BROADCAST_FAILED"
  | "SETTLEMENT_ALREADY_COMMITTED"
  | "QUOTE_STALE"
  | "STATE_CHANGED"
  | "REORGED";

export class MarketError extends Error {
  readonly code: MarketErrorCode;
  constructor(code: MarketErrorCode, message: string) {
    super(`[${code}] ${message}`);
    this.name = "MarketError";
    this.code = code;
  }
}
